# fly.toml file generated for alura-linguagens on 2023-04-05T12:55:26-03:00

app = "alura-linguagens"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "gru"
processes = []

[build]
  image = "gustavogoes/linguagensapi:latest"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
